### ISSUE TITLE
Crash when creating Animstrips

### ISSUE THREAD

**Issue by mixelon** [earok/scorpion-editor-demos#119]
Looks a lot like this:

![Screenshot 2021-01-14 201940](https://user-images.githubusercontent.com/1368213/104644874-3e9d7b00-56a6-11eb-93ea-fb1f1c96891e.png)

If I quit and reopen Scorpion it has created the file though so.. its not that big of a problem. :)

**Comment by earok** [comment]
I -think- this should be fixed now, at least that exact error shouldn't come back. Feel free to reopen or post a new issue if another crash happens when adding a new animstrip.
