### ISSUE TITLE
"Run Level" feature request

### ISSUE THREAD

**Issue by mixelon** [earok/scorpion-editor-demos#120]
Not sure if I should put feature requests here, but the ability to run the game from any level for testing purposes would be super handy when dealing with big projects. (i'm using a room of teleporters for now, which is functional, but means making a done of extra nonsense codeblocks?)

**Comment by earok** [comment]
Totally fine to add requests here. This particular feature would be good to have.

**Comment by earok** [comment]
Implemented via the ability to set a different startup script
