### ISSUE TITLE
Ability to turn off all isplatform/solids for foreground layer 

### ISSUE THREAD

**Issue by mixelon** [earok/scorpion-editor-demos#149]
this might already be possible but bear with me. 😅

Could the foreground layer not pay any attention to platform/solid tags? as its in the foreground you could just put the relevent platform type behind the foreground layer.. currently you have to have two copies of a solid looking tile if you want to, (for example) make secret passages. if the fg layer ignored platform/solid tags that wouldnt be necessary.

**Comment by earok** [comment]
Untested, but this will be in the next update
