### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by JohnArcher** [earok/scorpion-editor-demos#15]
Hi earok,

to test the Scorpion editor it would be need if could zip it from time to time and upload it to the releases tab here on github. It would be easier to download just the editor and not have to clone or download the whole repo.
It is no problem to release alpha versions there and tag them accordingly, so "release" does not mean that it has to be a perfect and final released version.

Cheers!

**Comment by earok** [comment]
Hey John,

Done ;) thanks for having faith of the heart in the project

https://github.com/earok/scorpion-editor-demos/releases

**Comment by JohnArcher** [comment]
Thanks, earok! Hehe, and yeah, I've got faith of the heart and faith in you because you know the Enterprise. :-)

Live long and prosper!
