### ISSUE TITLE
Asset type labels in list selectors

### ISSUE THREAD

**Issue by mixelon** [earok/scorpion-editor-demos#151]
When you have tons of sprites, actors, codeblocks etc the names are often too similar, so when you use search in the list view it'd be a really nice usability improvement if it had (sprite) (actor) etc next to the entries in the list.. Or if it subcategorised them in the search results?

**Comment by earok** [comment]
I've done this for the next build in the expression editor (which is used for conditionals, set variables, maybe some other places)
