### ISSUE TITLE
Seam in Copper gradients

### ISSUE THREAD

**Issue by mixelon** [earok/scorpion-editor-demos#155]
I don't know if this happens on every map or just incredibly wide ones, but at about 840 pixels down there's a seam in the copper sky.

https://youtu.be/3Y1A7Q7mwrk

The seam only appears on AGA amigas in WinUAE and FS-UAE.. But it displays slightly different behaviour if the copper is an OCS friendly or AGA one.. (its a black line on 24bit skies and a crease in OCS ones).. If I set it to just emulate an A3000 they don't appear. (you can replicate it in CMO latest build by pressing 3 and going to the right long enough to go through two teleports.)

**Comment by earok** [comment]
Done I guess? Please let me know if you see anything like it again.
