### ISSUE TITLE
Adding sound effects and MODs

### ISSUE THREAD

**Issue by weiju** [earok/scorpion-editor-demos#166]
Hi, is there any way to add sound effects and MODs through the UI ?
I noticed the "Audio&Anim5" tab is the only one missing a "+" sign to add these, is there a different way to add sound effect files ? I saw the included game projects (e.g. Super Go Down the Hole) support sound, but grepping through the text files, I didn't find the path reference to the sounds or MODs.

**Comment by earok** [comment]
Hi there, the files just need to be copied into the project folder, as long as they're in the project folder (or a subfolder) they'll be visible in the project. There's no "+" icon to import them because there's no ability in Scorpion to create or convert mod or sound effects.
