### ISSUE TITLE
Can this be used for games other than platformers/action?

### ISSUE THREAD

**Issue by saucefrog** [earok/scorpion-editor-demos#167]
Can this engine be used to develop adventure games with still images and no on-screen character or strategy games with multiple sprites to control?

**Comment by earok** [comment]
There have been experiments with "visual novel" style adventure games (such as the Ace Attorney demo in the unofficial pack - https://github.com/earok/unofficial-scorpion-demos)

In regards to strategy games, it's never been done, and I think in theory it might be too difficult to do - pathfinding is always tricky and mouse support (only in the latest versions of the engine) is limited to the game window, it can't cross over to UI panels.
