### ISSUE TITLE
scorpion_editor.exe does not start

### ISSUE THREAD

**Issue by JohnArcher** [earok/scorpion-editor-demos#17]
I downloaded the release package and tried to start the editor either via `Run Scorpion Editor.bat` as well open the Editor folder in file explorer and double click `scorpion_editor.exe`.

Then programm does ask me for the project folder. After I select one (in my case I selected the shipped `Demo Projects` folder) nothing happens. If I check the Windows event view I got this (sorry for some German in there, I run the German version of Windows 10):

`Anwendung: scorpion_editor.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Exception
   bei Gemini.AppBootstrapper.GetInstance(System.Type, System.String)
   bei Caliburn.Micro.IoC.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
   bei scorpion_editor.Modules.Base.Output(System.String)
   bei scorpion_editor.Modules.Base.Error(System.String, System.String, System.Nullable1<Int32>)
   bei scorpion_editor.App.App_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   bei System.Windows.Threading.DispatcherUnhandledExceptionEventHandler.Invoke(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   bei System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   bei System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
   bei System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)`

and

`Name der fehlerhaften Anwendung: scorpion_editor.exe, Version: 1.0.0.0, Zeitstempel: 0xe34a6d11
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.18362.719, Zeitstempel: 0x4061c730
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00114192
ID des fehlerhaften Prozesses: 0x73f8
Startzeit der fehlerhaften Anwendung: 0x01d6136b11b2fee0
Pfad der fehlerhaften Anwendung: F:\Downloads\ScorpionEditor\Editor\scorpion_editor.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll`

I am running Windows 10 Home 1909.

**Comment by earok** [comment]
Thanks for letting me know. Could I please get you to try the following?

- Delete ApplicationState.bin in the Editor folder
- Open one of the subfolders in Demo Projects, rather than the Demo Projects folder itself

**Comment by JohnArcher** [comment]
Tried both, but does not help. Programm crashes with same error messages.

**Comment by earok** [comment]
https://github.com/earok/scorpion-editor-demos/releases/download/v20.04.15/scorpion_installer.zip

Can you please try this installer? I'm hoping it solves the issue (note that the installer doesn't come with the demos, but it should be possible to open the demos from the other zip)

**Comment by JohnArcher** [comment]
Yes, this works! A project is corretly opened. Thanks a lot! Was it because of missing .NET framework stuff?

I noticed that when I cancel the dialog for asking a project the editor shortly opens and closes immediately (no error logging in event viewer).

**Comment by earok** [comment]
Great! I'll make the installer an option for future releases, and close this ticket. I'm not totally sure, but I suspect it might have been something .NET related that was missing.

Closing the app if no project is selected is the by-design behavior at the moment - Scorpion needs to have a project open to work (though opening an empty folder will prompt for creating a new project)
